AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  pShardCount:
    Type: Number
    Description: Number of Shards (1 shard => 1,000 eps / 1MBs)
    Default: 1

Resources:

  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: String
      ShardCount: !Ref pShardCount
      Tags: 
        - Key: Environment 
          Value: Production
