AWSTemplateFormatVersion: 2010-09-09

Description: Terminates a stack at a scheduled time

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Environment Setup
      Parameters:
      - pInfraStack

      
    ParameterLabels:
      pInfraStack:
        default: Infra stack name

Parameters:
  pExpirationDate:
    Type: Date

#------------------------------------------------------------------------------
# Exported variables
#------------------------------------------------------------------------------



Resources:

#------------------------------------------------------------------------------
# Exported variables
#------------------------------------------------------------------------------

Outputs: