AWSTemplateFormatVersion: '2010-09-09'

Description: Test for nested stack termination

Parameters:
  TTL:
    Type: Number
    Description: Time-to-live in minutes for the stack.
    Default: 2
    MinValue: 2

Resources:
  T800:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://sidford-cf-training.s3.eu-west-2.amazonaws.com/t800.yml
      Parameters:
        StackName: !Ref 'AWS::StackName'
        TTL: !Ref 'TTL'
